Autenticação
conab-devs/conab-frontend-mobile pull request #16
Opened 2020-11-10 12:16 UTC by hdev14

## Descrição :pencil:
Foi desenvolvido a tela de autenticação (login) do aplicativo, o estilo inícial da tela de "criar conta" e o layout padrão com o barra de navegação (bottom tab) para as outras telas. Além disso, também foi adicionado o Reactroton no modo de desenvolvimento para facilitar o debugging.

**Issues :pushpin:**
#1 

## Informações adicionais
>Marque se alguma dessas opções foram adicionadas/desenvolvidas

- [ ] Nova dependência :heavy_plus_sign:
- [ ] Dependência removida :heavy_minus_sign:
- [ ] Testes unitários ou de integração :white_check_mark:
- [ ] Nova migração para o Banco de Dados :card_file_box:
- [ ] Alteração no gitignore :see_no_evil:
- [ ] Refatoração de código :recycle:

https://reactnavigation.org/docs/getting-started
https://github.com/infinitered/reactotron

2020-11-11 13:22 UTC, FrankKleiton requested changes
Seria interessante um botão de logout para apagar o email e senha do storage.

2020-11-11 13:26 UTC, FrankKleiton requested changes
O botão de esqueci senha não está funcionando.

2020-11-11 13:33 UTC, FrankKleiton requested changes
Não sei se é só no meu device, mas a quantia de margin bottom dos ícones do navigation está praticamente inexistente e a top está muito pequena. No design tem bem mais.

2020-11-11 13:33 UTC, FrankKleiton commented
Tá show, depois de fazer as alterações que apontei vai estar perfekt. Muito bom.

2020-11-12 00:30 UTC, hdev14 commented on src/Routes.js
> +import SignOut from './screens/SignUp';
Acho q já modifiquei... talvez não tenha enviado o commit.

2020-11-12 00:32 UTC, hdev14 commented
> O botão de esqueci senha não está funcionando.

Foi mal, pensei que essa feature não entraria agr na autenticação.

2020-11-12 00:36 UTC, hdev14 commented
> Não sei se é só no meu device, mas a quantia de margin bottom dos ícones do navigation está praticamente inexistente e a top está muito pequena. No design tem bem mais.

Eu tinha explicado isso para vcs, mas eu ja entendi como módifica o bottomTab. Porém o do header é assim mesmo o design não levou em consideração que o android e o IOS possuem headers diferentes.

2020-11-24 13:51 UTC, hdev14 commented
@FrankKleiton @lucasemanuel acho que eu resolvi todos os comentários.

2020-11-24 14:27 UTC, FrankKleiton approved these changes

2020-11-24 14:29 UTC, lucasemanuel approved these changes

2020-11-24 20:57 UTC, merged